### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lucas-Fonte** [Lucas-Fonte/notify-kotlin-kafka#1]
## Application

- [ ] Create application
- [ ] Run application
- [ ] Setup Apache Kafka using Docker Compose
- [ ] Configure Kord
- [ ] Add tests

## Infrastructure

- [ ] Run application within different K8s pods ( Producers and Consumers )
- [ ] Add observability
- [ ] Configure deployment
- [ ] Configure Github Action
